#!/usr/bin/env python3
"""Regenerate src/lexirise/card/BenchFixtures.cpp from the binding reference's own data.

The card bench (P4) shows exactly the reference's words: reference/card-reference.html's B (the two
books, their words and saved levels) and FILL (the "Low on page" lines) tables are read and written out
as C++. Synthetic data, already public in docs/v0.1.

  python3 scripts/lexipoint/gen_bench_fixtures.py [--docs <repo>/docs/v0.1] [--check]

--check exits non-zero when the committed file differs (the fixtures drifted from the reference).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]  # firmware/
DOCS = REPO.parent / "docs/v0.1"  # the Lexipoint repo's docs, next to firmware/
OUT = REPO / "src/lexirise/card/BenchFixtures.cpp"
LEVELS = {0: "Level::Tracked", 1: "Level::Learning", 2: "Level::Fresh", 3: "Level::Known"}


def js_object(src: str):
    """The reference's object literals as JSON: bare keys and numeric keys quoted, .5 → 0.5."""
    src = src.strip().rstrip(";")
    src = re.sub(r"([{,])\s*([A-Za-z_][A-Za-z0-9_]*)\s*:", r'\1"\2":', src)
    src = re.sub(r"([{,])(\d+):", r'\1"\2":', src)
    src = re.sub(r":\.(\d)", r":0.\1", src)
    return json.loads(src)


def cstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def line(tokens) -> str:
    return "{" + ", ".join("{" + cstr(t[0]) + (f", {t[1]}" if len(t) > 1 else ", -1") + "}" for t in tokens) + "}"


def generate(html: str) -> str:
    b_src = html[html.index("const B={"):html.index("const LV=")]
    f_src = html[html.index("const FILL="):html.index("const pageLines")]
    books = js_object(b_src[b_src.index("{"):])
    filler = js_object(f_src[f_src.index("{"):])
    trad = re.search(r"only example is Traditional \(([^)]+)\)", html)
    out = ['''// Generated by scripts/lexipoint/gen_bench_fixtures.py from reference/card-reference.html (its B and FILL
// tables). Edit the reference, not this file, and regenerate. Synthetic data: nothing here came from the API.

#if LEXIRISE

#include "BenchFixtures.h"

namespace lexipoint::card {
namespace {

// The reference marks the word in a sentence with <u>…</u>.
MarkedText marked(const std::string& withU) {
  MarkedText out;
  const size_t open = withU.find("<u>");
  const size_t close = withU.find("</u>");
  if (open == std::string::npos || close == std::string::npos || close < open) {
    out.text = withU;
    return out;
  }
  out.text = withU.substr(0, open) + withU.substr(open + 3, close - open - 3) + withU.substr(close + 4);
  out.markStart = open;
  out.markLength = close - open - 3;
  return out;
}

''']
    for key, lang in (("ja", "Language::Japanese"), ("zh", "Language::Chinese")):
        b = books[key]
        out.append(f"BenchBook make{key.capitalize()}() {{\n  BenchBook b;\n  b.language = {lang};\n")
        out.append("  b.lines = {" + ",\n             ".join(line(l) for l in b["lines"]) + "};\n")
        out.append("  b.filler = {" + ",\n              ".join(line(l) for l in filler[key]) + "};\n")
        out.append(f"  b.contextFirst = {b['ctx'][0]};\n  b.contextEnd = {b['ctx'][1]};\n  b.start = {b['start']};\n")
        for w in b["W"]:
            out.append(f"  {{\n    CardWord w;\n    w.language = {lang};\n")
            out.append(f"    w.reading = {cstr(w['k'])};\n")
            if w.get("rk"):
                out.append(f"    w.romaji = {cstr(w['rk'])};\n")
            out.append(f"    w.word = {cstr(w['w'])};\n")
            if w.get("b"):
                out.append(f"    w.badge = {cstr(w['b'])};\n")
            if w.get("s"):
                out.append(f"    w.surface = {cstr(w['s'])};\n")
            if w.get("f"):
                out.append(f"    w.conjugation = {cstr(w['f'])};\n")
            out.append(f"    w.partOfSpeech = {cstr(w['p'])};\n")
            out.append("    w.senses = {" + ", ".join(cstr(x) for x in w["m"]) + "};\n")
            out.append(f"    w.rank = {w['r']};\n    w.frequency = {w['sc']!r}f;\n")
            chars = ", ".join("{" + cstr(c[0]) + ", " + cstr(c[1]) + ", " + cstr(c[2] or "") + ", " + cstr(c[3]) + "}"
                              for c in w["ch"])
            out.append("    w.chars = {" + chars + "};\n")
            if w.get("form"):
                # The reference's "dictionary form" row is the card's own string (CardStrings::dictionaryForm).
                forms = ", ".join("{" + cstr(f[0]) + (', "", true}' if f[1] == "dictionary form"
                                                      else ", " + cstr(f[1]) + "}") for f in w["form"])
                out.append("    w.forms = {" + forms + "};\n")
            if w.get("met"):
                out.append(f"    w.metBeforeBook = {cstr(w['met'][0])};\n    w.metBefore = marked({cstr(w['met'][1])});\n")
            if w.get("trad"):
                out.append("    w.examplesOnlyTraditional = true;\n")
                if trad:
                    out.append(f"    w.traditionalForm = {cstr(trad.group(1))};\n")
            out.append("    b.words.push_back(std::move(w));\n  }\n")
        out.append("  b.saved.assign(b.words.size(), Level::None);\n")
        for k, v in b["save"].items():
            out.append(f"  b.saved[{k}] = {LEVELS[v]};\n")
        out.append("  return b;\n}\n\n")
    out.append('''}  // namespace

const BenchBook& benchJapanese() {
  static const BenchBook book = makeJa();
  return book;
}

const BenchBook& benchChinese() {
  static const BenchBook book = makeZh();
  return book;
}

}  // namespace lexipoint::card

#endif  // LEXIRISE
''')
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--docs", type=pathlib.Path, default=DOCS)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = generate((args.docs / "reference/card-reference.html").read_text())
    if args.check:
        # Compare ignoring formatting (the committed file is clang-formatted).
        squash = lambda s: re.sub(r"\s+", "", s)
        if squash(text) != squash(OUT.read_text()):
            print("BenchFixtures.cpp differs from the reference: regenerate", file=sys.stderr)
            return 1
        print("BenchFixtures.cpp matches the reference")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
